### ISSUE TITLE
Authenticator.exe ERROR

### ISSUE THREAD

**Issue by laza-niaina** [acheong08/ChatGPT-to-API#108]
`panic:_ runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x20 pc=0x114896b]

goroutine 1 [running]:
authenticator/auth.(*Authenticator).Begin(0xc0000e4420)
        C:/Users/Fujitsu/ChatGPT-to-API/tools/authenticator/auth/auth.go:97 +0x66b
main.main()
        C:/Users/Fujitsu/ChatGPT-to-API/tools/authenticator/main.go:122 +0x4a5`

**Comment by maminiainalaic** [comment]
mine is 

Location: begin
Status code: 403
Details: <html>
...
</html>
Embedded error: 
error: Check details
panic: (*auth.Error) 0xc000516000

goroutine 1 [running]:
main.main()
	/home/maminiainalaic/ChatGPT-to-API/tools/authenticator/main.go:130 +0xb5e

**Comment by Yamamoto-2** [comment]
>Same
Location: begin
Status code: 403
Details: <html>
……
</html>
Embedded error: error: Check details
[GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware
[logs.txt](https://github.com/acheong08/ChatGPT-to-API/files/12271083/logs.txt)
 already attached.

**Comment by oldweipro** [comment]
Give it a try with my repository [oldweipro/ChatGPT-to-API](https://github.com/oldweipro/ChatGPT-to-API) and see if the fix-403 branch can solve your issue.
试一下我的仓库 [oldweipro/ChatGPT-to-API](https://github.com/oldweipro/ChatGPT-to-API) fix-403分支 的是否可以解决你的问题
